#!/bin/bash

# Load resources

#xrdb -merge .Xresources

# Set up an icon tray
# stalonetray &

# Fire up apps

# nautilus &

#xscreensaver -no-splash &

#if [ -x /usr/bin/nm-applet ] ; then
#   nm-applet --sm-disable &
#fi

#emacs-25.1 --daemon &

#emacsclient -c &

#exec xmonad
